export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const ADD_BOOK = "ADD_BOOK";
export const FILTER_BOOKS = "FILTER_BOOKS";
export const FILTER_BOOKS_BY_TITLE = "FILTER_BOOKS_BY_TITLE";
export const FILTER_BOOKS_BY_AUTHOR = "FILTER_BOOKS_BY_AUTHOR";
export const FILTER_BOOKS_BY_GENRE = "FILTER_BOOKS_BY_GENRE";
export const FILTER_BOOKS_BY_ISBN = "FILTER_BOOKS_BY_ISBN";
